### ISSUE TITLE
Not working on version 1.15.10

### ISSUE THREAD

**Issue by Jing-Linux** [jostephd/combat-info-theme#5]
error message:
`20210308 10:01:15 error display: Theme 'combat-info' not found. Trying the default theme.`
Then there is no option to change to this theme later in game.

**Comment by jostephd** [comment]
@Jing-Linux I'm sorry to hear it doesn't work, but I'm afraid that I don't currently have time to play Wesnoth or to look into bugs. If you don't get an answer here, try asking on the Wesnoth discord or forums.

Anyone who wants to look into this issue is welcome to do so. If you have questions for me or need extra permissions on the repo, get in touch.

**Comment by Jing-Linux** [comment]
I've solved this problem. I download the _mail.cfg file in this repo, and then put it in the /share/wesnoth/data/themes/ directory, then install it from the add-on server to be able to choose the theme in game.

**Comment by jostephd** [comment]
Thanks for sharing the solution! :pray:
